### ISSUE TITLE
event rate

### ISSUE THREAD

**Issue by TorryAN** [Jee-King/ICCV2021_Event_Frame_Tracking#1]
Hi, 
Thanks for your interesting work,  fusing events and frames for tracking is worth exploring. I train your network and get similar test results. A minor question, how to statistic event rate?

**Comment by Zizzzzzzz** [comment]
Can you please share the train code? @TorryAN

**Comment by Jee-King** [comment]
Hi, we compute the rate of event stream generated during the recordings as follows: for the event stream of each sequence, we first discretize its time dimension into 1ms intervals. We then count the number of events of each interval and calculate the average number of events of all intervals as the event rate.

**Comment by TorryAN** [comment]
Thanks. I got it.

**Comment by TorryAN** [comment]
Thanks. I got it.
